[project]
name = "agents-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub[cli]>=0.31.2",
    "ipywidgets>=8.1.7",
    "jupyter>=1.1.1",
]
